FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY registro.html /usr/share/nginx/html/registro.html
COPY rankings.html /usr/share/nginx/html/rankings.html
COPY to.html /usr/share/nginx/html/to.html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80