apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: proyecto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 043207749401.dkr.ecr.us-east-1.amazonaws.com/parcial-backend:1.0
          env:
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_DB
              value: proyecto_db
          ports:
            - containerPort: 5000