apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: proyecto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 043207749401.dkr.ecr.us-east-1.amazonaws.com/parcial-frontend:1.0
          ports:
            - containerPort: 80